export type VendorStatus = 'draft'|'pending'|'approved'|'rejected'|'suspended'|'inactive';
export type Vendor = { id:string; userId:string; name:string; slug:string; owner:string; category:string; service:string; city:string; locations:string[]; experience:number; description:string; summary:string; price:number; phone:string; whatsapp:string; email:string; image:string; gallery:string[]; documents:string[]; seoTitle?:string; seoDescription?:string; status:VendorStatus; published:boolean; featured:boolean; priority:number; featuredStart:string; featuredEnd:string; remarks:string; sample:boolean; };
import type {PlanId} from './plans';
export type VendorSubscription={plan:PlanId;status:'selected'|'created'|'authenticated'|'active'|'pending'|'halted'|'cancelled'|'completed'|'expired';gatewayId?:string;gatewayPlanId?:string;trialEndsAt?:string;trialUsedAt?:string;paidCount?:number;reminderClaimedAt?:string;reminderSentAt?:string;updatedAt:string};
export type PendingRegistration={id:string;email:string;phone:string;passwordHash:string;plan:PlanId;verified:boolean;verificationHash?:string;sessionHash?:string;autopayConsentAt:string;expires:number;subscription?:VendorSubscription;completedUserId?:string};
export type User = { id:string; email:string; phone:string; passwordHash:string; role:'vendor'|'admin'; verified:boolean; phoneVerified?:boolean; phoneVerifiedAt?:string; subscription?:VendorSubscription; };
export type Enquiry = { id:string; vendorId:string; name:string; contact:string; city:string; date:string; service:string; message:string; consent:true; status:'new'|'contacted'|'closed'; createdAt:string; };
export type Taxon = {name:string; slug:string; active:boolean; services?:string[]; phase?:1|2; position?:number};
export type State = { vendors:Vendor[]; users:User[]; registrations:PendingRegistration[]; enquiries:Enquiry[]; sessions:{hash:string; userId:string; expires:number}[]; tokens:{hash:string; userId:string; kind:'verify'|'reset'|'mobile'; expires:number}[]; categories:Taxon[]; locations:Taxon[]; audit:{id:string; actor:string; action:string; target:string; remarks:string; at:string}[] };
