import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Phone,MessageCircle,MapPin,ArrowLeft,Sparkles} from 'lucide-react';
import {Header,Footer,PreviewNotice} from '@/components/ui';
import {EnquiryForm} from '@/components/forms';
import {readState} from '@/lib/store';
import {publicVendors,money,isFeatured} from '@/lib/directory';
import {readOnlyDeployment} from '@/lib/config';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const v=publicVendors((await readState()).vendors).find(x=>x.slug===slug);return {title:v?.name??'Vendor not found',description:v?.summary,alternates:{canonical:`/vendors/${slug}`},robots:v?undefined:{index:false,follow:false},openGraph:v?{title:v.name,description:v.summary,url:`/vendors/${slug}`,images:[{url:v.image,alt:v.name}]}:undefined};}
export default async function Profile({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const v=publicVendors((await readState()).vendors).find(x=>x.slug===slug);if(!v)notFound();const readOnly=readOnlyDeployment();return <><Header/><main id="main" className="container page-main"><Link className="back-link" href="/vendors"><ArrowLeft size={16}/> Back to vendors</Link><div className="profile-heading"><div><span className="section-label">{v.category}</span><h1>{v.name}</h1><p className="location"><MapPin size={16}/>{v.locations.join(' · ')}{isFeatured(v)&&<span className="badge inline"><Sparkles size={12}/>Featured</span>}</p></div><div className="profile-price"><span>Starting from</span><strong>{money(v.price)}</strong>{v.category==='Catering & Food'&&<small>per person</small>}</div></div><div className="gallery">{(v.gallery.length?v.gallery:['/occanova-logo.jpg']).map((image,i)=><a key={i} href={image} target="_blank" rel="noreferrer" aria-label={`Open portfolio image ${i+1}`}><img src={image} alt={`${v.sample?'Illustrative event photograph':v.name+' portfolio'} ${i+1}`}/></a>)}</div><div className="profile-layout"><section><span className="section-label">THE PEOPLE BEHIND THE WORK</span><h2>A little about {v.name}</h2><p className="description">{v.description}</p><div className="profile-facts"><div><span>Experience</span><strong>{v.experience} years</strong></div><div><span>Available in</span><strong>{v.locations.join(', ')}</strong></div><div><span>Specialisation</span><strong>{v.service||v.category}</strong></div></div><h3>Let’s start a conversation</h3>{v.sample?<p className="notice">This is an illustrative sample business with no real contact details.</p>:<div className="contact-actions"><a className="button" href={`tel:${v.phone.replace(/[^+0-9]/g,'')}`}><Phone size={17}/>Call vendor</a><a className="button outline" target="_blank" rel="noreferrer" href={`https://wa.me/${v.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent(`Hello ${v.name}, I found your business on Occanova and would like to enquire about an event.`)}`}><MessageCircle size={17}/>WhatsApp</a></div>}</section><aside className="panel enquiry-panel"><h2>Tell them about your day.</h2><p>Share a few details to get the conversation started.</p><EnquiryForm vendor={v} readOnly={readOnly}/></aside></div></main><Footer/><PreviewNotice/></>;}
