import Link from 'next/link';
import {CheckCircle2,Clock3,FilePenLine} from 'lucide-react';
import type {Vendor} from '@/lib/types';

export function ReviewStatus({vendor,publicListing,accessReason}:{vendor?:Vendor;publicListing:boolean;accessReason?:string}){
 const status=vendor?.status??'draft';const pending=status==='pending',approved=status==='approved';
 const title=pending?'Your profile is waiting for review':approved?publicListing?'Your business is live on Occanova':'Your profile is approved':status==='rejected'?'A few changes are needed':['inactive','suspended'].includes(status)?'Your profile is currently unavailable':'Let’s get your business ready';
 const copy=pending?'Your submission reached Occanova. We’ll notify you here and by email when a decision is made.':approved?publicListing?'Customers can discover your business and send enquiries. Keep an eye on your enquiry inbox.':accessReason||'Your listing is private. Occanova needs to publish it before customers can find you.':status==='rejected'?'Use the feedback below to update your profile, then submit it for another review.':['inactive','suspended'].includes(status)?'Contact info@occanova.com for help restoring your profile.':'Complete your business details, then submit your profile for approval.';
 const Icon=pending?Clock3:approved?CheckCircle2:FilePenLine;
 return <section id="review-status" className={`review-status-card ${status}`} aria-labelledby="review-status-title"><div className="review-status-icon"><Icon size={28}/></div><div className="review-status-copy"><span className="section-label">PROFILE PROGRESS</span><h2 id="review-status-title">{title}</h2><p>{copy}</p><ol className="review-progress" aria-label="Profile review progress"><li className={!pending&&!approved?'current':'complete'}>1. Complete profile</li><li className={pending?'current':approved?'complete':''}>2. Occanova review</li><li className={approved?'current':''}>3. Approved</li></ol>{vendor?.submittedAt&&<small>Submitted {new Date(vendor.submittedAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'})}</small>}{vendor?.remarks&&['approved','rejected','suspended','inactive'].includes(status)&&<div className="review-feedback"><strong>Reviewer’s feedback</strong><p>{vendor.remarks}</p></div>}<div className="review-status-actions">{publicListing&&vendor?<Link className="button small" href={`/vendors/${vendor.slug}`}>View public profile</Link>:<a className="button small" href="#profile">{pending?'View submitted details':status==='rejected'?'Update profile':'Continue profile'}</a>}<a className="button outline small" href="#enquiries">Open enquiries</a></div></div></section>;
}
