import Link from 'next/link';
import {Header,Footer} from '@/components/ui';
import {planIds,subscriptionPlans} from '@/lib/plans';
export const metadata={title:'Terms and conditions',robots:{index:false,follow:false,noarchive:true}};
export default function Terms(){return <><Header/><main id="main" className="container legal">
 <h1>Terms & conditions</h1><p>Last updated: 28 September 2026. These terms apply to the Occanova platform. Contact <a href="mailto:info@occanova.com">info@occanova.com</a> for support and billing questions.</p>
 <h2>About Occanova</h2><p>Occanova helps customers discover event vendors across India and send enquiries. An enquiry is an introduction, not a booking or service agreement. Event arrangements, availability and vendor service charges must be agreed directly with the vendor. A platform subscription does not guarantee enquiries, bookings, revenue or featured placement.</p>
 <h2>Vendor accounts and subscriptions</h2><p>New vendors select a plan, verify their email and authorize Razorpay AutoPay before their account is activated. Accounts and uploaded material must belong to the person or business registering. Keep your credentials private and supply accurate business details.</p>
 <div className="table-wrap"><table><thead><tr><th>Plan</th><th>Monthly fee, GST included</th><th>Portfolio photos</th></tr></thead><tbody>{planIds.map(id=><tr key={id}><td>{subscriptionPlans[id].name}</td><td>₹{subscriptionPlans[id].monthlyRupees}</td><td>Up to {subscriptionPlans[id].portfolioLimit}</td></tr>)}</tbody></table></div>
 <h2>Two-month free trial and AutoPay</h2><p>Eligible new vendors receive two calendar months without a monthly platform fee. The selected plan’s limits apply during the trial. The trial schedule is created when AutoPay setup opens; the exact first debit date appears in Razorpay Checkout and your vendor studio. Your payment provider may process a small authorization amount. Monthly charges begin on the agreed date through the authorized mandate. The mandate contains up to 96 monthly billing cycles; it does not renew indefinitely. Reauthorizing or changing plans does not grant another free trial.</p>
 <h2>Profile review and access</h2><p>Profiles require administrator review before publication. Editing a published profile returns it to draft until reviewed again. An inactive subscription or a profile exceeding its plan’s photo allowance can be hidden from search and restricted from edits or uploads. Plan changes do not automatically remove your photos; remove excess photos before saving. Only features currently described in the account interface are available.</p>
 <h2 id="cancellation-refunds">Cancellation and refunds</h2><p>Cancel AutoPay from <Link href="/dashboard#subscription">Plan & billing</Link> before the scheduled debit to stop future subscription charges. Cancellation is immediate and ends subscription access; it can hide your listing. Logging out or stopping use of the website does not cancel AutoPay.</p><p>Subscription fees are generally non-refundable once a billing cycle has been charged. We review duplicate payments, incorrect charges and substantiated service issues case by case. This policy does not exclude refunds or other remedies required by applicable law.</p><p>For a billing dispute, email <a href="mailto:info@occanova.com">info@occanova.com</a> with your registered email, payment reference, date, amount and a description of the issue. Never send passwords, card credentials or bank OTPs. Approved refunds are processed through the original payment method where supported; bank and payment-provider processing times vary. A refund request does not itself cancel the mandate.</p>
 <h2>Content and platform use</h2><p>Upload only material you own or have permission to use. Do not publish misleading information, impersonate others, expose private customer data or submit unlawful material. Occanova may hide profiles or suspend accounts for misuse. Vendors remain responsible for their own services and any agreements made with customers.</p>
 <h2>Support and changes</h2><p>Contact <a href="mailto:info@occanova.com">info@occanova.com</a> for account, service or billing complaints. Material changes to subscription pricing or billing require updated authorization where needed; the website does not silently alter your existing Razorpay mandate.</p>
 </main><Footer/></>;}
