import {Header,Footer} from '@/components/ui';
export const metadata={title:'Privacy policy',robots:{index:false,follow:false,noarchive:true}};
export default function Privacy(){return <><Header/><main id="main" className="container legal">
 <h1>Privacy policy</h1><p>Last updated: 28 September 2026. Occanova handles the information described below to operate its vendor discovery platform. For privacy requests, contact <a href="mailto:info@occanova.com">info@occanova.com</a>.</p>
 <h2>Information we collect</h2><p>Registration stores your email, mobile number, securely hashed password, selected plan, email and mobile verification status, and AutoPay consent. Subscription records include mandate identifiers, billing status and trial dates. The mobile number verified for your vendor account is shown as the public phone number on your listing. Vendor profiles also contain the business information, other public contact details, logo and portfolio you provide. Uploaded verification documents are private. Enquiries contain the customer’s name, contact information, event date, location, message and consent to share those details.</p>
 <h2>How information is used and shared</h2><p>We use this information to authenticate accounts, review profiles, manage subscriptions, deliver verification and service emails, prevent abuse and connect customers with vendors. Approved business details and portfolio photos appear in the public directory. Enquiries are available to the relevant vendor and Occanova administrators. Password hashes, private documents and internal review notes are not part of public vendor profiles.</p>
 <h2>Payment and service providers</h2><p>Razorpay handles payment and AutoPay authorization. Occanova stores payment references and subscription status, not full card details or bank OTPs. Hosting is provided through Vercel; production account records use MongoDB, transactional email uses Resend, and private uploads use Cloudflare R2 through the S3-compatible storage interface. These providers process information needed to deliver their services. Illustrative photography and fonts may be requested from Unsplash and Google Fonts, which receive standard browser request information.</p>
 <h2>Cookies and security</h2><p>Essential session cookies keep you signed in and allow you to resume registration. Verification and password-reset links have limited validity. Private uploads are accessed through permission checks and short-lived download links. Security controls reduce risk but cannot guarantee that every system or internet connection is free from unauthorized access.</p>
 <h2>Retention and your requests</h2><p>We retain account, enquiry and subscription records to operate the service and meet applicable obligations. Some unfinished registrations expire; records linked to a payment mandate may be retained to resolve authorization or billing issues. You can correct business details in your vendor studio and request access, correction or deletion by emailing <a href="mailto:info@occanova.com">info@occanova.com</a> from your registered email. We may verify your identity and retain records needed for billing disputes or legal obligations. A deletion request does not automatically cancel AutoPay; cancel the mandate in Plan & billing as well.</p>
 <h2>Contact</h2><p>Send privacy questions and complaints to <a href="mailto:info@occanova.com">info@occanova.com</a>. Do not include passwords, payment credentials or OTPs in your message.</p>
 </main><Footer/></>;}
