import {redirect} from 'next/navigation';
import Link from 'next/link';
import {currentUser} from '@/lib/auth';
import {readState} from '@/lib/store';
import {Workspace} from '@/components/workspace';
import {ProfileForm,EnquiryTable,PasswordForm} from '@/components/forms';
import {hasStorage} from '@/lib/config';
export const metadata={robots:{index:false,follow:false,noarchive:true}};
export const dynamic='force-dynamic';
export default async function Dashboard(){const user=await currentUser();if(!user)redirect('/login');if(user.role==='admin')redirect('/admin');const s=await readState();const v=s.vendors.find(x=>x.userId===user.id);const enquiries=s.enquiries.filter(x=>x.vendorId===v?.id);const completion=v?Math.round([v.name,v.owner,v.category,v.service,v.city,v.description,v.phone,v.whatsapp,v.email,v.image,v.gallery.length].filter(Boolean).length/11*100):0;return <Workspace email={user.email}><div className="page-heading"><span className="section-label">A LITTLE SPACE FOR BIG PLANS</span><h1>{v?`Hello, ${v.owner.split(' ')[0]}.`:'Welcome to Occanova.'}</h1><p>Let’s make your business ready for its next celebration.</p></div><div className="stat-grid"><div><span>Profile completion</span><strong>{completion}%</strong><progress value={completion} max={100}/></div><div><span>Review status</span><strong className="capitalize">{v?.status??'Draft'}</strong></div><div><span>New enquiries</span><strong>{enquiries.filter(x=>x.status==='new').length}</strong></div><div><span>Public listing</span><strong>{v?.published&&v.status==='approved'?'Published':'Not published'}</strong></div></div>{v?.remarks&&<div className="notice"><strong>Occanova’s review:</strong> {v.remarks}</div>}<section id="profile" className="panel"><div className="section-heading"><h2>Your business profile</h2>{v?.published&&v.status==='approved'&&<Link href={'/vendors/'+v.slug}>View public profile</Link>}</div><ProfileForm vendor={v} categories={s.categories} locations={s.locations} email={user.email} phone={user.phone} storageEnabled={hasStorage()}/></section><section id="enquiries" className="panel"><h2>Your enquiries</h2><EnquiryTable rows={enquiries.toReversed()} vendors={s.vendors}/></section><section id="account" className="panel account-panel"><h2>Account & security</h2><p>Signed in as {user.email}. Changing your password signs out all sessions.</p><PasswordForm/></section></Workspace>;}
